### PR TITLE
Fix some GCC warnings

### LINKED ISSUE #1542: When compiling GHEX we see #pragma unroll warnings
```
In file included from /home/biddisco/src/ghex/include/ghex/structured/regular/.././field_utils.hpp:16,
                 from /home/biddisco/src/ghex/include/ghex/structured/regular/../field_descriptor.hpp:15,
                 from /home/biddisco/src/ghex/include/ghex/structured/regular/field_descriptor.hpp:14,
                 from /home/biddisco/src/ghex/tests/communication_object_2.cpp:15:
_deps/gridtools-src/include/gridtools/common/array.hpp:137: warning: ignoring #pragma unroll  [-Wunknown-pragmas]
  137 | #pragma unroll
```

### PR DESCRIPTION
**Pull request by havogt**
Fixes #1542 and others.

### CODE REVIEW

File: include/gridtools/common/array.hpp [hunk 1]
```diff
@@ -134,7 +134,6 @@ namespace gridtools {
     // in case we need a constexpr version we need to implement a recursive one for c++11
     template <typename T, typename U, size_t D>
     GT_CONSTEXPR GT_FUNCTION bool operator==(array<T, D> const &a, array<U, D> const &b) {
-#pragma unroll
```
Comment (havogt) [inline include/gridtools/common/array.hpp:137]: Do you think we have CUDA code relying on this? Should we run perftests?

**Comment by havogt** [comment]
launch jenkins

File: include/gridtools/common/array.hpp (hunk 1 above)
Comment (anstaf) [reply include/gridtools/common/array.hpp:137]: I don't understand what is wrong with that pragma? What GCC warns about here?

File: include/gridtools/storage/builder.hpp [hunk 2]
```diff
@@ -44,7 +44,9 @@ namespace gridtools {
                             return false;
                     return true;
                 };
+#ifdef _OPENMP
```
Comment (anstaf) [inline include/gridtools/storage/builder.hpp:47]: I think that warning against unknown pragmas is stupid.
AFAIK, the standard says that unknown pragmas should be ignored. Why we can not use that guaranty?
Is it possible just to add `-Wno-unknown-pragmas` after `-Wall`?

File: include/gridtools/storage/sid.hpp [hunk 3]
```diff
@@ -33,7 +33,8 @@ namespace gridtools {
 
             constexpr dimension_kind get_dimension_kind(int i, size_t n_dim) {
                 return i < 0 ? dimension_kind::masked
-                             : i + 1 == n_dim ? dimension_kind::innermost : dimension_kind::dynamic;
+                             : static_cast<std::size_t>(i) + 1 == n_dim ? dimension_kind::innermost
```
Comment (anstaf) [inline include/gridtools/storage/sid.hpp:36]: will changing `n_dim` parameter to `int` work as well?

**Review by anstaf — CHANGES_REQUESTED** [review]

File: include/gridtools/common/array.hpp (hunk 1 above)
Comment (havogt) [reply include/gridtools/common/array.hpp:137]: That's an nvcc pragma, the gcc pragma would be `#pragma GCC unroll D`

File: include/gridtools/storage/builder.hpp (hunk 2 above)
Comment (havogt) [reply include/gridtools/storage/builder.hpp:47]: I would propose to be pragmatic:
- It will be in a limited number of places
- Setting `-Wno-unknown-pragmas` would have to be done in each user code, we cannot/should not do it for the user. We will get complaints from users in the future. We even got one from an internal user @mbianco.
- Apparently, the gcc community decided that it's worth warning about that, let's accept the decision.

File: include/gridtools/storage/sid.hpp (hunk 3 above)
Comment (havogt) [reply include/gridtools/storage/sid.hpp]: done

File: include/gridtools/common/array.hpp (hunk 1 above)
Comment (mbianco) [reply include/gridtools/common/array.hpp:137]: Perftests would be good.

I think we can tell the users to do something like this (found on stackoverflow):
```
#pragma GCC diagnostic push 
#pragma GCC diagnostic ignored "-Wunused-local-typedefs"
#include <QtXmlPatterns>
#pragma GCC diagnostic pop
```

Comment (mbianco) [reply include/gridtools/common/array.hpp:137]: well, it does not seem to work for me ...

Comment (havogt) [reply include/gridtools/common/array.hpp:137]: Maybe we should just wrap this in an `#ifdef __CUDACC__` then we don't have to do perftests ;)

File: include/gridtools/storage/builder.hpp (hunk 2 above)
Comment (anstaf) [reply include/gridtools/storage/builder.hpp:47]: OK, I am convinced. Let us guard all pragmas with the ifdefs

File: include/gridtools/common/array.hpp (hunk 1 above)
Comment (anstaf) [reply include/gridtools/common/array.hpp:137]: I agree with Hannes about ifdef.
Moreover, we probably should do
```
#ifdef __GNUG__
#pragma GCC unroll
#ifndef __CUDACC__
#pragma unroll  
#endif
```
to be consistent with the approach we take with OMP pragmas

IMHO it doesn't make sense to perftest here. Pragmas can not make the generation worse.

**Review by anstaf — APPROVED** [review]

File: include/gridtools/common/array.hpp (hunk 1 above)
Comment (mbianco) [reply include/gridtools/common/array.hpp:137]: The lack of pragmas can make the generation worse

Comment (mbianco) [reply include/gridtools/common/array.hpp:137]: Maybe `#idndef _GNUC_` is better, since other compilers also use `#pragma unroll`?

**Comment by havogt** [comment]
launch jenkins
